export default{
    path:'/mine',
    component:()=>import('@/views/mine'),
    children:[
        {
            path:'center',
            component:()=>import('@/views/mine/center'),
        },
        {
            path:'login',
            component:()=>import('@/components/Login'),
        },{
            path:'register',
            component:()=>import('@/components/Register'),
        },{
            path:'findPassword',
            component:()=>import('@/components/FindPassword'),
        },
        {
            path:'/mine',
            redirect:'center'
        }
    ]
}